### ISSUE TITLE
Can't delete

### ISSUE THREAD

**Issue by Jassper** [hzeller/augenmass#1]
Anyway to add functionality to delete unwanted measurements?

**Comment by hzeller** [comment]
This isn't implemented yet. I accept pull requests _hint_ _hint_ :)

**Comment by Jassper** [comment]
I saw that in your readme file, but I'm new to Github, not sure how to do a pull request. But I'll try to figure it our.

Thanks

**Comment by hzeller** [comment]
You essentially fork the code in git, make the needed changes and then ask back upstream to merge it (which is called 'pull request').

**Comment by Jassper** [comment]
Ahh, that's what I thought. But I'm not a programmer so I can't make the changes. Is there a way to 'request' a change?

**Comment by hzeller** [comment]
This is free software so it ultimately lives from people contributing code. Since I am busy with other stuff right now, I don't get around working on it right away, but it is certainly on my TODO list (and with your request got bumped a bit up). If you want to contribute in other ways than code, you could work out how you think it might look like (I think, it would require a separate mode 'select' which allows to select lines already drawn - so that it is possible to delete them with 'Del' or 'Backspace'). Having a good UI idea will help later implementation.

You could as well convince someone you know making such a change and then doing the pull request so that it is merged with upstream.

**Comment by Jassper** [comment]
OK, I'll check around my Makerspace and see if anyone knows Java well enough to make an attempt.

Thanks

**Comment by hzeller** [comment]
Cool (Note, it is JavaScript though, entirely different)

**Comment by hzeller** [comment]
Fixed in PR #5

**Comment by 0lm** [comment]
Very useful tool, thanks for this! Sorry for reviving this thread, but I noticed that angles can't be deleted. Any chance to add that, too?

**Comment by hzeller** [comment]
I just noticed that there is a PR #6  waiting I was missing so far and have to review. Is this what you need ?
